### ISSUE TITLE
No Badge Mode (Just show N Items Selected)

### ISSUE THREAD

**Issue by WillGeller** [CuppaLabs/angular2-multiselect-dropdown#253]
Thank you for building a great ng2 multi-select component!

Would you consider implementing a no badge mode where you can specify the text to display when the dropdown is collapsed, and it would simply say `N Items Selected`.  Let me know if you would like to see a mock-up or would be open to a PR with this feature.

I like the component a lot but members of my team would prefer this to be an option, and I would prefer not to have to maintain a fork.

**Comment by CuppaLabs** [comment]
@WillGeller Thank you for the feedback and I see your requirement to be an add on to this component. PR's are welcome. You can raise one let include this feature.

**Comment by seraries** [comment]
I agree this would be a great feature (and I also second the Thank You for building this component!!) and I see it is marked as "Done" but I'm not sure how I can utilize this feature--is there anything in the documentation about it? For my use case, when all items are selected, instead of showing the first N selected badges, I'd just like to show text stating "ALL", for instance. So having a configurable setting, like you do for `text` but for "Text to be show in the dropdown, when ALL items are selected." would be SUPER awesome! 
Thank you again!
