### ISSUE TITLE
Not able to re render previously saved data on multiselect 

### ISSUE THREAD

**Issue by samir-kamble** [CuppaLabs/angular2-multiselect-dropdown#272]
I have a Reactive form with dynamically adding form groups with a multi select field. I am able to get input from dropdown but not able re render the same structure back into the select dropdown.

Can anyone help.

**Comment by dagardiner** [comment]
There's a typo in multiselect.component.ts line 221 - "splice" should be "slice"; that causes the original array to be emptied (since splice modified the original array - which is what you've bound to), and the selectedItems to not work properly.  You can temporarily work around by removing the limitSelector option.

**Comment by CuppaLabs** [comment]
resolved. iz available in v2.9.1

**Comment by samir-kamble** [comment]
May I know what would be the solution?
