### ISSUE TITLE
How do I style using CSS instead of HTML?

### ISSUE THREAD

**Issue by wilburrito** [CuppaLabs/angular2-multiselect-dropdown#572]
Hi, newbie here. How do I style the dropdown using CSS instead of using the Themes that you provided. Also, could you elaborate on what "_Include the default.theme.css in angular-cli.json (for versions below angular 6) and angular.json (for version 6 or more)._" means? I don't even know how to implement the default theme. Please advise. Thanks in advance, from an Angular newbie trying to be like you!

**Comment by CuppaLabs** [comment]
@wilburrito Thank you for writing to me. Appreciate your enthusiasm to learn. 
1) You can write your styles using styles.css file in the root folder and override the default classes of dropdown. However, i recommend using the theme file to customise the style.
2) angular.json is a configuration file for your angular projects and libraries. You can add external js and css files in the file so that you need not export them explicitly in html file.
If you need any further assistance, feel free to reach out to me. Will be more than happy to help you learn.
Closing this issues as it is not a functional issue.
